use_frameworks!
platform :ios, '11.0'

target 'SheetyColors_Example' do
  pod 'SheetyColors', :path => '../'

  target 'SheetyColors_Tests' do
    inherit! :search_paths

    pod 'Quick', '2.2.0'
    pod 'Nimble', '8.0.7'
    pod 'SnapshotTesting', '1.7.2'
  end
end
