use_frameworks!
platform :ios, '11.0'

target 'SheetyColors_Example' do
  pod 'SheetyColors', :path => '../'

  target 'SheetyColors_Tests' do
    inherit! :search_paths

    pod 'Quick', '2.1.0'
    pod 'Nimble', '8.0.2'
    pod 'SnapshotTesting', '1.5.0'
  end
end
