use_frameworks!
platform :ios, '10.0'

target 'SheetyColors_Example' do
  pod 'SheetyColors', :path => '../'

  target 'SheetyColors_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
    pod 'SnapshotTesting', '~> 1.5'
  end
end
